Repository Inteli-College/2025-1A-T12-EC05-G03, pull requests merged in 2025-03, with the labels that each got.

#76 Feat/firmware dobot
  .github/pull_request_template.md
  firmware/.gitignore
  firmware/CadastrarPosicoes.py
  firmware/fita.json
  firmware/ilhas.py
  firmware/posicoes_ilhas.json
  firmware/requirements.txt
Labels: enhancement

#81 fix: Atualiza e complementa documentação
  docs/docs/sprint-2/docs-código/evodasprint.md
  media/codigo/codeposi.png
  media/codigo/codeteclado.png
Labels: documentation

#104 Feature/tcrt5000
  src/firmware/codigos_apoio/sensor_distancia.cpp
Labels: Feature

#113 docs: adiciona diagrama de blocos
  docs/docs/sprint-3/diagrama-de-blocos/_category_.json
  docs/docs/sprint-3/diagrama-de-blocos/diagrama-de-blocos.md
  media/diagramablocos1.png
  media/diagramablocos2.png
  media/diagramablocos3.png
Labels: documentation

#118 docs: ajusta imagem e fluxo do diagrama de blocos
  docs/docs/sprint-3/diagrama-de-blocos/diagrama-de-blocos.md
  media/diagramablocos2.png
  media/diagramablocos3.png
Labels: documentation

#136 feat: implementa nova rota de puxar a ultima coisa da fila
  src/api/routes/pedidos.py
  src/api/routes/prescricoes.py
Labels: Feature

#145 feature: adiciona tela de login e cadastro
  src/front-end/cadastro.html
  src/front-end/index.html
  src/front-end/login.html
  src/front-end/styles.css
Labels: Feature

#146 Feature/api+movimentacao do robo
  .gitignore
  src/firmware/ilhas.py
  src/firmware/qrcode.py
  src/firmware/sensor_distancia.py
  src/requirements.txt
Labels: Feature

#148 fix: correção na importação
  src/api/main.py
Labels: bug

#149 feat: adiciona front-end da home-page
  src/front-end/home/css-file.css
  src/front-end/home/home-page.html
  src/front-end/home/js-file.js
Labels: Feature

#150 Feature/rotas crud em tudo
  docs/docs/sprint-3/docs-api/rotas.md
  src/api/models/lote.py
  src/api/routes/home.py
  src/api/routes/logs.py
  src/api/routes/lotes.py
  src/api/routes/pedidos.py
  src/api/routes/prescricoes.py
Labels: Feature

#153 Feature/finaliza-front-end
  src/firmware/qrcode.py
  src/front-end/cadastro.html
  src/front-end/css/css-file.css
  src/front-end/css/estoque-css.css
  src/front-end/css/historico.css
  src/front-end/css/modal.css
  src/front-end/css/styles-login.css
  src/front-end/css/styles.css
  src/front-end/estoque.html
  src/front-end/historico.html
  src/front-end/home-page.html
  src/front-end/home/js-file.js
  src/front-end/index.html
  src/front-end/js/estoque-js.js
  src/front-end/js/historico.js
  src/front-end/js/js-file.js
  src/front-end/js/menu.js
  src/front-end/js/modal.js
  src/front-end/login.html
Labels: Feature

#155 Feature/dinamica front end
  src/front-end/cadastro.html
  src/front-end/css/modal.css
  src/front-end/css/styles-login.css
  src/front-end/home-page.html
  src/front-end/js/js-file.js
  src/front-end/js/modal.js
Labels: Feature

#168 docs: adiciona estrutura de documentação
  docs/docs/sprint-4/banco_e_Crud/_category_.json
  docs/docs/sprint-4/banco_e_Crud/atualizacao_banco.md
  docs/docs/sprint-4/banco_e_Crud/historico_operacoes.md
  docs/docs/sprint-4/banco_e_Crud/operacoes_crud.md
  docs/docs/sprint-4/funcionalidades-sistema/Acesso_Funcionalidades.md
  docs/docs/sprint-4/funcionalidades-sistema/Atualizacao_Rotas.md
  docs/docs/sprint-4/funcionalidades-sistema/Integracao_Backend_Frontend.md.md
  docs/docs/sprint-4/funcionalidades-sistema/Leitor_QR_Code.md
  docs/docs/sprint-4/funcionalidades-sistema/Manipulacoes_Robo.md
  docs/docs/sprint-4/funcionalidades-sistema/_category_.json
  docs/docs/sprint-4/interface-usuario/_category_.json
  docs/docs/sprint-4/interface-usuario/elementos_selecionados.md
  docs/docs/sprint-4/interface-usuario/funcionalidades_implementadas.md
  docs/docs/sprint-4/interface-usuario/processo_criativo.md
  docs/docs/sprint-4/template-pasta/_category_.json
  docs/docs/sprint-4/template-pasta/template.md
Labels: documentation
